# Generated by Django 5.0.6 on 2024-08-18 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener 8 dígitos', regex='^\\d{8}$')])),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3, message='El nombre debe tener al menos 3 letras.'), django.core.validators.RegexValidator(message='El nombre solo puede contener letras.', regex='^[a-zA-Z]+$')])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3, message='El nombre debe tener al menos 3 letras.'), django.core.validators.RegexValidator(message='El apellido solo puede contener letras.', regex='^[a-zA-Z]+$')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido')])),
                ('numer_phone', models.CharField(default='+54', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener 10 dígitos después del prefijo +54', regex='^\\+54\\d{10}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
