# Generated by Django 5.0.6 on 2024-08-18 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3, message='El apellido debe tener al menos 3 letras.'), django.core.validators.RegexValidator(message='El apellido solo puede contener letras.', regex='^[a-zA-Z]+$')]),
        ),
    ]
